routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Rutas RESTFUL
Route::resource('usuarios','Administrador\UsuarioController');
Route::resource('cuentas','CuentasController');
Route::get('retiro_credito',['as'=>'cuentas.retiro_credito', 'uses' => 'CuentasController@retiroCredito']);
Route::get('retiro_debito',['as'=>'cuentas.retiro_debito', 'uses' => 'CuentasController@retiroDebito']);
Route::get('abono_debito',['as'=>'cuentas.abono_debito', 'uses' => 'CuentasController@abonoDebito']);
Route::get('cantidad/retiro', 'CuentasController@CantidadRetiroCredito');
Route::get('cantidad/retiroDebito', 'CuentasController@CantidadRetiroDebito');
Route::get('cantidad/abonoDebito', 'CuentasController@CantidadAbonoDebito');

Route::resource('transacciones','TransaccionesController');

// API - consulta todas las transacciones
Route::get('/v1/admin/api/transacciones', 'Administrador\Api\TransaccionesApiController@getApiTransacciones');
// API - consulta los usuarios
Route::get('/v1/admin/api/usuarios', 'Administrador\Api\UsuarioApiController@index');

app/Http/Controllers/Administrador/UsuarioController.php
<?php

namespace App\Http\Controllers\Administrador;
Use App\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->user()->authorizeRoles(['admin']);
        $usuarios = User::all();
        return view('admin.usuarios.index', compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/usuarios/index.blade.php
@if (Auth::user()->rol=="admin")
    {{-- resources/views/admin/dashboard.blade.php --}}

@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Usuarios del Sistema</h1>
@stop

@section('content')
    
    <div class="box box-solid box-primary">
        <h4>Bienvenido: {{ Auth::user()->nombre }} {{ Auth::user()->apellido_paterno }}  {{ Auth::user()->apellido_materno }} </h4>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        
        <thead>
            <tr>
                <th>Tipo de Usuario</th>
                <th>Nombre</th>
                <th>Apellido Paterno</th>
                <th>Apellido Materno</th>
                <th>Telefono</th>
                <th>Email</th>
                <th>Estatus</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($usuarios as $usuario)
                <tr>
                <td>{{ $usuario->rol }}</td>
                <td>{{ $usuario->nombre }}</td>
                <td>{{ $usuario->apellido_paterno }}</td>
                <td>{{ $usuario->apellido_materno }}</td>
                <td>{{ $usuario->telefono }}</td>
                <td>{{ $usuario->email }}</td>
                @if ($usuario->estatus =1)
                <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></td>   
                @else
                <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>     
                @endif
                <td><a class="btn btn-primary" href="{{-- {{ route('admin.usuarios.edit')}} --}}">Editar</a></td> 
                
                <td><a class="btn btn-primary" href="{{-- {{ route('admin.usuarios.destoy')}} --}}">Eliminar</a></td> 
                
                </tr>
            @endforeach
                
        </tbody>
    </table>
    <a href="{{route('home')}}">< Regresar</a>
    
   
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop
@else
    @include('layouts.404')
@endif